# Generated by Django 6.0.7 on 2026-07-23 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Urbanizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('direccion', models.CharField(max_length=300)),
                ('num_pistas', models.PositiveSmallIntegerField(default=1)),
                ('hora_apertura', models.TimeField(default='08:00')),
                ('hora_cierre', models.TimeField(default='22:00')),
                ('duracion_franja_minutos', models.PositiveSmallIntegerField(default=90)),
                ('max_reservas_por_vivienda', models.PositiveSmallIntegerField(default=1)),
                ('antelacion_maxima_dias', models.PositiveSmallIntegerField(default=7)),
                ('cancelacion_minima_horas', models.PositiveSmallIntegerField(default=2)),
                ('creada', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Urbanización',
                'verbose_name_plural': 'Urbanizaciones',
            },
        ),
    ]
