# Generated by Django 6.0.7 on 2026-07-27 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='companeros',
            field=models.CharField(blank=True, max_length=200, verbose_name='Con quién juegas'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='recordatorio_enviado',
            field=models.BooleanField(default=False),
        ),
    ]
