# Generated by Django 6.0.7 on 2026-07-27 19:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0002_reserva_companeros_reserva_recordatorio_enviado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultadoPartido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente de confirmación'), ('confirmado', 'Confirmado'), ('disputado', 'Disputado')], default='pendiente', max_length=20)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_confirmacion', models.DateTimeField(blank=True, null=True)),
                ('confirmado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resultados_confirmados', to=settings.AUTH_USER_MODEL)),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultados_creados', to=settings.AUTH_USER_MODEL)),
                ('equipo_a', models.ManyToManyField(related_name='resultados_equipo_a', to=settings.AUTH_USER_MODEL)),
                ('equipo_b', models.ManyToManyField(related_name='resultados_equipo_b', to=settings.AUTH_USER_MODEL)),
                ('reserva', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='resultado', to='reservas.reserva')),
            ],
            options={
                'verbose_name': 'Resultado de partido',
                'verbose_name_plural': 'Resultados de partido',
                'ordering': ['-reserva__fecha', '-reserva__hora_inicio'],
            },
        ),
        migrations.CreateModel(
            name='SetResultado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveSmallIntegerField()),
                ('juegos_equipo_a', models.PositiveSmallIntegerField()),
                ('juegos_equipo_b', models.PositiveSmallIntegerField()),
                ('es_super_tiebreak', models.BooleanField(default=False)),
                ('resultado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sets', to='reservas.resultadopartido')),
            ],
            options={
                'verbose_name': 'Set',
                'verbose_name_plural': 'Sets',
                'ordering': ['numero'],
                'unique_together': {('resultado', 'numero')},
            },
        ),
    ]
