# Generated by Django 6.0.7 on 2026-07-28 08:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0003_resultadopartido_setresultado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resultadopartido',
            name='equipo_a',
        ),
        migrations.RemoveField(
            model_name='resultadopartido',
            name='equipo_b',
        ),
        migrations.CreateModel(
            name='Participante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipo', models.CharField(choices=[('A', 'Equipo A'), ('B', 'Equipo B')], max_length=1)),
                ('nombre_invitado', models.CharField(blank=True, max_length=100, verbose_name='Nombre (sin perfil)')),
                ('resultado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participantes', to='reservas.resultadopartido')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='participaciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Participante',
                'verbose_name_plural': 'Participantes',
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('nombre_invitado', ''), ('usuario__isnull', False)), models.Q(('usuario__isnull', True), models.Q(('nombre_invitado', ''), _negated=True)), _connector='OR'), name='participante_usuario_o_invitado')],
            },
        ),
    ]
