# Generated by Django 6.0.7 on 2026-07-23 15:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('urbanizaciones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('urbanizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portales', to='urbanizaciones.urbanizacion')),
            ],
            options={
                'ordering': ['nombre'],
                'unique_together': {('urbanizacion', 'nombre')},
            },
        ),
        migrations.CreateModel(
            name='Vivienda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('piso', models.CharField(max_length=10)),
                ('puerta', models.CharField(blank=True, max_length=5)),
                ('portal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viviendas', to='viviendas.portal')),
            ],
            options={
                'ordering': ['portal', 'piso', 'puerta'],
                'unique_together': {('portal', 'piso', 'puerta')},
            },
        ),
    ]
