# Generated by Django 6.0.7 on 2026-07-23 15:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('urbanizaciones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='Pista 1', max_length=100)),
                ('activa', models.BooleanField(default=True)),
                ('urbanizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pistas', to='urbanizaciones.urbanizacion')),
            ],
            options={
                'ordering': ['urbanizacion', 'nombre'],
                'unique_together': {('urbanizacion', 'nombre')},
            },
        ),
    ]
