# Generated by Django 6.0.7 on 2026-07-27 09:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pistas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BloqueoPista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('motivo', models.CharField(blank=True, max_length=200)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('pista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bloqueos', to='pistas.pista')),
            ],
            options={
                'verbose_name': 'Bloqueo de pista',
                'verbose_name_plural': 'Bloqueos de pista',
                'ordering': ['fecha', 'hora_inicio'],
            },
        ),
    ]
